name: Continuous Integration

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Execute CI script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          rustflags: ""
      - name: Execute CI script
        uses: ./.github/actions/ci_script

  build-msrv:
    name: MSRV - Execute CI script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust MSRV
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.66.0
          rustflags: ""
      - name: Execute CI script
        uses: ./.github/actions/ci_script

  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r *.md
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}

  mismatcher:
    name: Check for mismatched dependencies (those that have more than one version)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.inputs.rev }}"
      - name: Install latest Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          rustflags: ""
      - name: Execute CI script
        uses: ./.github/actions/ci_script
        with:
          ci-flags: "mismatcher"
